### PR TITLE
Forum functionality for #184

### PR DESCRIPTION
**Pull request by nathanhilbert**
**Work in progress... do not merge**
relates to #184 
- [ ] fix granular permissions
- [x] inherit the base theme of FIND
- [x] point to the right static
- [x] review all code and change routes
- [ ] fix travis hate
- [x] need to check the x-csrf header as well
- [ ] authentication unit tests (at very least)
- [ ] Style the forums page
- [ ] Finish the management links

### CODE REVIEW

**Comment by nathanhilbert** [comment]
This can is testable at this point, but shouldn't be merged into master.
A few things are required...
- make sure WTF_CSRF_ENABLED= False is in your settings.py file
- run pip install -r requirements.txt
- run ostool db migrate
- then go to localhost:5000/admin/forum

**Comment by dstepp** [comment]
Update the complexity estimate please.

**Comment by nathanhilbert** [comment]
Overall, 10-20 hours total for the polishing and upkeep of this module.  On the scale of 5 is “I have complete ignorance” and 1 is “everything is known”, I'm a 2.

**Comment by nathanhilbert** [comment]
Everything is working at this point.  Permissions need to be verified, the management section needs to be completed, and there are a few buttons that need to be removed or fixed (like marked as read).  I'll leave the decision to the team as to whether to merge depending on the push to the server timeframe.  The unchecked to do in this PR can be split out into separate tickets if it makes sense to merge this now.

**Comment by nathanhilbert** [comment]
A few screenshots
databank-openspending
databank-openspending2
databank-openspending3
databank-openspending4

**Comment by brandtheisey** [comment]
I checked out this PR locally to test and now neither setenv.bat or ostool run db migrate work. I added the **WTF_CSRF_ENABLED = False** and ran the **pip install -r requirements.txt**

screen shot 2015-08-03 at 12 53 23 pm

**Comment by nathanhilbert** [comment]
Thanks for testing.  That is what travis is complaining about too (https://travis-ci.org/USStateDept/FPA_Core/builds/73802006#L713), but it wasn't happening on my local.  
Dah.. I see what I did.  I'm ignoring [settings.py files](https://github.com/USStateDept/FPA_Core/blob/99eb9560b91cacfa454325999bda839f0368bbce/.gitignore#L29).  I'll rename and push tonight.

**Comment by brandtheisey** [comment]
I'll give it another shot after you push again.

**Comment by nathanhilbert** [comment]
Travis is still failing with a different error, but seems like the test environment more than anything.  Give it another try.

**Comment by brandtheisey** [comment]
I have it working locally. 

Is there any reason to not put it on AWS, understanding it's a initial implementation and that there may be bugs? We'd like to get more of the team's eyes on it.

**Comment by nathanhilbert** [comment]
There are two unit tests failing related to authentication and permissions when I run 

```
$ runtests.bat
```

Also, I haven't tested a regular non-admin user or the moderator user type and I haven't tested the rest of the site functionality.
Permissions aren't that big of deal since the site is locked down at the moment.  If these are acceptable, then it can be merged and pushed to the server.

**Comment by brandtheisey** [comment]
Those are all acceptable levels of risk. So I'm going to merge this pr and push it to AWS this afternoon.

**Pull request merged**
