### PR TITLE
A few javascript edits

### PR DESCRIPTION
**Pull request by nathanhilbert**
A few tweaks to how data is handled to cut down on server calls and slim down browser memory requirements.

### CODE REVIEW

**Comment by nathanhilbert** [comment]
Ready to merge.  Please test beforehand.
To checkout a remote branch:

```
$git fetch
$git checkout jswork
```

**Comment by backnotprop** [comment]
test the 'categories' link
it does not appear to work properly in your branch...
For me it links to the 'build a visualization' instead

**Comment by backnotprop** [comment]
Actually it is doing this for the 'Data' link as well

**Comment by backnotprop** [comment]
In the comparator slide-menu, I am not seeing countries.

**Comment by nathanhilbert** [comment]
Thanks @mdramos.  The Data link is correct from what I see on find.state.gov, but you are right, I got a little copy happy for the categories.

I'm seeing the countries listed in the comparator slide-menu.  Please include JS errors or anything else that would be helpful.

**Comment by backnotprop** [comment]
sorry for not including the error...

it is:
TypeError:  window.loader.loadCountries is not a function       dataviz.js:1692:5

investigating this further now...

**Comment by nathanhilbert** [comment]
Maybe a hard reload or clear cache and reload?  My dataviz.js file only has 1673 lines.

**Comment by mdramos** [comment]
That was it. The ladder issues are fixed now, looking good

**Comment by backnotprop** [comment]
That did fix all issues that I was seeing. JS looks good

**Pull request merged**
