### PR TITLE
Rework of the Data API

### PR DESCRIPTION
**Pull request by nathanhilbert**
- [x] unit tests for api calls
- [x] fix date range
- [x] do model json of available options
- [x] Do caching
- [x] integrate into front-end
- [x] output for ~~JSON~~, xls, and csv

optional
- [ ] add fields param if neccessary

### CODE REVIEW

**Comment by nathanhilbert** [comment]
@mdramos This is ready to merge.  I noticed two things:
- the map was not being styled due to a mismatch of maxyears and available years in the data @sc0ttius is this something with the slider and years calculations?
- the cards can't be flipped twice on the /visualization page. I select one indicator, then can't flip a card for a second.

Other than that, I think things are going smoothly.  I need to dig deeper into the cache next week and see what we can do. Please merge, and we can work from master.

**Comment by backnotprop** [comment]
@nathanhilbert the cards not flipping is a bug that I will fix tomorrow. I can make the merge tomorrow morning.

**Comment by backnotprop** [comment]
@sc0ttius will wait for you to look at the maxyears issue noted above before a merge

**Comment by sc0ttius** [comment]
I believe the way the year was being used for the maps was different from the way the years were being used for the highcharts. I haven't done anything for the maps. We should adjust the year for the maps similar to how it is used for bar or bubble charts.

**Comment by backnotprop** [comment]
I did the merge and pushed

**Pull request merged**
